trigger:
- main

pool:
  vmImage: windows-2022

steps:
- powershell: | 
        @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  displayName: 'Installing  Chocolatery'

- powershell: | 
       
  displayName: 'Installing  .net core framework'

- powershell: | 
          choco install azure-cli
          choco install git
          winget install Microsoft.DotNet.SDK.Preview  

  displayName: 'Installing  Rest of dependencies'

- powershell: | 
      
          winget install Microsoft.DotNet.SDK.Preview  
             
  displayName: 'Installing  .net 7'


- powershell: | 

            dotnet restore aspnetcoreapp.csproj --packages .nuget/ --runtime win-x86
            dotnet publish aspnetcoreapp.csproj -c Release --no-restore --runtime win-x86 --no-self-contained -o ./tmp/publish
            cd tmp\publish
            Compress-Archive . publish.zip

  displayName: 'Building Application '



- powershell: | 

          az webapp deploy --resource-group mm --name mm-skedda-app-webapp60126-eastus --src-path publish.zip --type zip

  displayName: 'Deploying Application to Azure'
