trigger:
  - main

pool:
  vmImage: windows-2022

steps:
- powershell: | 

            Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
        
  displayName: 'Installing  Azure cli'

- powershell: | 
          
          $ProgressPreference='Silent' Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.3.2691/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          winget install Microsoft.DotNet.SDK.Preview  
             
  displayName: 'Installing  netcore 7 sdk'

- powershell: | 

          az login --service-principal -u e86f1bfa-58b0-47f2-9dac-6f61de199e08 -p gw88Q~N1Udw_fEEkpneMtwb3idoZhkK2bnywWbMP --tenant 8af79369-0252-4816-893a-d143b54885e3

  displayName: 'Login to Azure cli using Service principal '

          

- powershell: | 

            dotnet restore aspnetcoreapp.csproj --packages .nuget/ --runtime win-x86
            dotnet publish aspnetcoreapp.csproj -c Release --no-restore --runtime win-x86 --no-self-contained -o ./tmp/publish
            cd tmp\publish
            Compress-Archive . publish.zip

  displayName: 'Building Application '



- powershell: | 

          az webapp deploy --resource-group mm --name mm-skedda-app-webapp60126-eastus --src-path publish.zip --type zip

  displayName: 'Deploying Application to Azure'
