pool:
  vmImage: windows-2022

steps:
- powershell: | 
                 Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

  displayName: 'Installing  Chocolatery'

- powershell: | 
          choco install azure-cli
          choco install terraform

  displayName: 'Installing  Rest of dependencies'

- powershell: | 

          terraform init
          terraform plan 
          terraform apply -yes

  displayName: 'Provisioning  resources in Terraform '

