trigger:
- main

pool:
  vmImage: windows-2022

steps:
- powershell: | 
        @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  displayName: 'Installing  Chocolatery'

- powershell: | 
          choco install azure-cli
          choco install git
          choco install terraform

  displayName: 'Installing  Rest of dependencies'

- powershell: | 

          terraform init
          terraform plan 
          terraform apply -yes

  displayName: 'deploy resources in Terraform '
